services:
  backend:
    image: parkpay-backend:ci
    build:
      context: .
      dockerfile: apps/backend/Dockerfile

    container_name: parkpay-backend

    env_file:
      - ./apps/backend/.env

    environment:
      NODE_ENV: production

    ports:
      - "3000:3000"

    volumes:
      - ./apps/backend/data:/app/apps/backend/data

    restart: unless-stopped

  frontend:
    image: parkpay-frontend:ci
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile

    container_name: parkpay-frontend

    env_file:
      - ./apps/frontend/.env

    ports:
      - "5173:80"
    volumes:
      - ./apps/frontend/src:/app/apps/frontend/src

    depends_on:
      - backend

    restart: unless-stopped

volumes:
  parkpay-data: